services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
      - ./entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    environment:
            GF_INSTALL_PLUGINS: volkovlabs-form-panel
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - ./grafana-dashboards:/var/lib/grafana/dashboards:rw
      - ./grafana-provisioning:/etc/grafana/provisioning:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

  data_streamer:
    build: .
    container_name: data_streamer
    privileged: true
    depends_on:
      - influxdb
    restart: on-failure:5
    env_file:
      - .env
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/spidev0.0:/dev/spidev0.0"
    volumes:
      - /sys/bus/w1/devices:/sys/bus/w1/devices:ro
  ngrok-grafana:
    image: ngrok/ngrok:latest
    container_name: ngrok-grafana
    env_file:
      - .env
    command: http grafana:3000
    depends_on:
      - grafana
    ports:
      - 4040:4040
  ngrok-influxdb:
    image: ngrok/ngrok:latest
    container_name: ngrok-influxdb
    environment:
      - NGROK_AUTHTOKEN=35jwfFv5NZsCLI9NoZbfq64NKG4_4N4TYtd3QdzjXg1xzxNhf
    command: http influxdb:8086
    depends_on:
      - influxdb
    ports:
      - 4041:4040
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8087:8087"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
    depends_on:
      - influxdb

volumes:
  influxdb-storage:
