services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
      - ./entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

  data_streamer:
    build: .
    container_name: data_streamer
    privileged: true
    depends_on:
      - influxdb
    restart: on-failure:5
    env_file:
      - .env
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/spidev0.0:/dev/spidev0.0"
    volumes:
      - /sys/bus/w1/devices:/sys/bus/w1/devices:ro
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    env_file:
      - .env
    command: http grafana:3000
    ports:
      - 4040:4040

volumes:
  grafana-storage:
  influxdb-storage:
